### PR TITLE
[9.0][mail_activity] add activities to systray

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This PR adds the management of activities to the systray.
image

@andreparames @hbrunn are you still interested on working on this in 9.0 and 10.0?

### CODE REVIEW

**Comment by hbrunn** [comment]
it turned out my customer wants an entirely different UI, no point in publishing this. So from my side in 10, no standard UI will come. If somebody needs it, better supersede my PR

**Comment by JordiBForgeFlow** [comment]
@hbrunn ok!

**Comment by JordiBForgeFlow** [comment]
@hbrunn should keep mail_activity module with just the data model then?

**Comment by hbrunn** [comment]
that was my original plan, but I don't see a problem in adding the standard UI there, and people like me have to overwrite this with whatever they need

**Pull request closed without merging**
